services:
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: bloglist-reverse-proxy-dev
    depends_on:
      - app

  app:
    image: bloglist-frontend-dev
    volumes:
      - ./bloglist-frontend/:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm install && npm run dev"
    depends_on:
      - server

  server:
    image: bloglist-backend-dev
    volumes:
      - ./bloglist-backend/:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm install && npm run dev"