services:
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    container_name: bloglist-reverse-proxy
    depends_on:
      - app
      - server

  app:
    build:
      context: ./bloglist-frontend
      dockerfile: Dockerfile
      target: production-stage
    container_name: bloglist-frontend
    depends_on:
      - server

  server:
    build:
      context: ./bloglist-backend
      dockerfile: Dockerfile
      target: production-stage
    container_name: bloglist-backend