# fly.toml app configuration file generated for bloglist-backend-old-voice-389 on 2025-04-15T13:34:40+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bloglist-backend-old-voice-389'
primary_region = 'mad'

[build]

[env]
  PORT = "3003"

[processes]
  app = "node src/index.js"

[http_service]
  internal_port = 3003
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/api/health/status"
  
[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
