### Get All Blogs
GET http://localhost:3003/api/blogs


### Create a New Blog
POST http://localhost:3003/api/blogs
Content-Type: application/json

{ 
    "author": "Mark Doe",
    "url": "https://codewithmark.com",
    "likes": 100
}