### [GET] - Get All Blogs:
GET http://localhost:3003/api/blogs


### [GET] - Get a Single Blog:
GET http://localhost:3003/api/blogs/67e997520be2a25633a39291


### [GET] - Get a Single Blog (Non-Existing ID):
GET http://localhost:3003/api/blogs/67e6c744892b9d5da14c9fb1


### [GET] - Get a Single Blog (Malformatted ID):
GET http://localhost:3003/api/blogs/1234


### [POST] - Create a New Blog:
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjVhNDIyYTg1MWI1NGE2NzYyMzRkMTdmOCIsImlhdCI6MTc0MzM3MTA0MiwiZXhwIjoxNzQzMzc0NjQyfQ.OMnABBdY6lZkNCcAxnRWTLG8VMmDzUhf-BeRKXd6qko

{ 
    "title": "Galileo Galilei",
    "author": "Galileo Galilei",
    "url": "https://en.wikipedia.org/wiki/Galileo_Galilei",
    "likes": 50
}


### [POST] - Create a New Blog (Invalid Data):
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjVhNDIyYTg1MWI1NGE2NzYyMzRkMTdmOCIsImlhdCI6MTc0MzM3MTA0MiwiZXhwIjoxNzQzMzc0NjQyfQ.OMnABBdY6lZkNCcAxnRWTLG8VMmDzUhf-BeRKXd6qko

{ 
    "author": "John Doe",
    "url": "https://codewithjohn.com",
    "likes": 100
}


### [POST] - Create a New Blog (Missing Token):
POST http://localhost:3003/api/blogs
Content-Type: application/json

{ 
    "author": "John Doe",
    "url": "https://codewithjohn.com",
    "likes": 100
}


### [PUT] - Update a Blog:
PUT http://localhost:3003/api/blogs/67e6c772892b9d5da14c9fbf
Content-Type: application/json

{
    "likes": 102
}


### [PUT] - Update a Blog (Non-Existing ID):
PUT http://localhost:3003/api/blogs/67e6c772892b9d5da14c9fb1
Content-Type: application/json

{
    "likes": 101
}


### [PUT] - Update a Blog (Malformatted ID):
PUT http://localhost:3003/api/blogs/1312
Content-Type: application/json

{
    "likes": 101
}


### [DELETE] - Delete a Blog:
DELETE http://localhost:3003/api/blogs/67e6c772892b9d5da14c9fbf


### [DELETE] - Delete a Blog (Malformatted ID):
DELETE http://localhost:3003/api/blogs/2131