services:
  app:
    image: hello-front-dev
    environment:
      - VITE_BACKEND_URL=http://localhost:3000
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app