### [GET] Get All Blogs:
GET http://localhost:3001/api/blogs


### [GET] Get All Blogs with Search:
GET http://localhost:3001/api/blogs?search=new


### [GET] Get Blog by ID:
GET http://localhost:3001/api/blogs/8


### [POST] Create Blog:
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3RAbWF0cml4LmNvbSIsImlkIjoxLCJpYXQiOjE3NDUwODExMDIsImV4cCI6MTc0NTA4NDcwMn0.XPp-ASdfIr0Q3PzGr3bKt4FLTHmouEsIkyUkNST4Bpc

{
    "title": "New Tech",
    "author": "Blog Doe",
    "url": "https://www.test4.com",
    "likes": 10
}


### [PUT] Update Blog:
PUT http://localhost:3001/api/blogs/2
Content-Type: application/json

{
    "likes": 101
}


### [DELETE] Delete Blog:
DELETE http://localhost:3001/api/blogs/10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3RAbWF0cml4LmNvbSIsImlkIjo2LCJpYXQiOjE3NDUwNjkxNzksImV4cCI6MTc0NTA3Mjc3OX0.S0KqQc2bOFlAmiZ6czJRbucpgYT0sP6XZ7kPknxgIvg