### Get All Users:
GET http://localhost:3001/api/users


### Create User:
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "root@matrix.com",
    "name": "Root User",
    "password": "rootpassword"
}


### Update User:
PUT http://localhost:3001/api/users/test2@matrix.com
Content-Type: application/json

{
    "username": "test3@matrix.com"
}


### Delete User:
DELETE http://localhost:3001/api/users/test3@matrix.com


