### Get All Users:
GET http://localhost:3001/api/users


### Create User:
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "test2@test.com",
    "name": "Test User",
    "password": "testpassword"
}


### Update User:
PUT http://localhost:3001/api/users/updatedTest
Content-Type: application/json

{
    "username": "test@matrix.com"
}


### Delete User:
DELETE http://localhost:3001/api/users/updatedTest@test.com


