### GET all patients
GET http://localhost:3001/api/patients


### GET a patient by ID
GET http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667


### POST a patient
POST http://localhost:3001/api/patients
Content-Type: application/json

{
    "name": "John Doe",
    "dateOfBirth": "1990-01-01",
    "gender": "male",
    "ssn": "1234567890",
    "occupation": "Software Engineer"
}
