### [Local][DELETE] - Delete Person:
DELETE http://localhost:3001/api/persons/67e465804394d9cb6bc79655


### [Remote][DELETE] - Delete Person:
DELETE https://phonebook-blue-lake-542.fly.dev/api/persons/2
