### [Local][GET] - All Persons:
GET http://localhost:3001/api/persons


### [Local][GET] - Single Person:
GET http://localhost:3001/api/persons/1


### [Remote][GET] - All Persons:
GET https://phonebook-blue-lake-542.fly.dev/api/persons


### [Remote][GET] - Single Person:
GET https://phonebook-blue-lake-542.fly.dev/api/persons/67e452e38d7cff4ec9653112