name: Health Check

on:
  # schedule:
  #   - cron: '40 21 * * *'
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check Pokedex Health
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://pokedex-divine-water-3533.fly.dev/health
          follow-redirect: false
          max-attempts: 3
          retry-delay: 5s
          retry-all: false
