name: Testing stuff

on:
  push:
    branches:
      - main

env:
  GITHUB_CONTEXT: ${{ toJson(github) }}
  COMMITS: ${{ toJson(github.event.commits) }}
  COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Github Context
        run: echo "$GITHUB_CONTEXT"
      - name: Commits
        run: echo "$COMMITS"
      - name: Commit Messages
        run: echo "$COMMIT_MESSAGES"